### ISSUE TITLE
thumbnail filenames

### ISSUE THREAD

**Issue by mnagel** [mnagel/gpsplot#27]
thumbnails for images with same name overwrite each other.
do something like hashing.

test if the go server can cope with it.

**Comment by cipold** [comment]
Don't know about the go server but as far as I understood the go server creates the thumbs on the fly so this issue has do be solved separately. For python preprocessing I used a simple md5 hash of the full image path as thumbnail filename.

**Comment by cipold** [comment]
Now thumbnails work with go server again - simple url hack putting the original filename into the url. Please someone clean up the Go code as these were my first lines of code and the chance of everything still being ok is low ;)
