### ISSUE TITLE
custom iconCreateFunction to support more than 3 cluster colors

### ISSUE THREAD

**Issue by mnagel** [mnagel/gpsplot#36]
currently the default is used, giving us three different cluster colors based on cluster size:
https://github.com/Leaflet/Leaflet.markercluster#all-options
```
		var c = ' marker-cluster-';
		if (childCount < 10) {
			c += 'small';
		} else if (childCount < 100) {
			c += 'medium';
		} else {
			c += 'large';
		}
```
we should roll our own and use a nice gradient from green to red

**Comment by cipold** [comment]
Done.
