### ISSUE TITLE
create a live demo and push it to some webspace

### ISSUE THREAD

**Issue by mnagel** [mnagel/gpsplot#51]
...and link it from the repo+description

**Comment by mnagel** [comment]
http://gpsplot-demo.lettink.de/

**Comment by pkern** [comment]
403 Forbidden. Außerdem hätte man auch gh-pages verwenden können? ;-)

**Comment by mnagel** [comment]
@fknittel ping

github pages: fette binaries (die bilder) gehen nicht so doll mit github pages afaik.

**Comment by fknittel** [comment]
Das Problem sollte eigentlich seit etwas mehr als zwei Stunden behoben sein. (Meine Skripte brauchen mehr Safeguards... ich hatte den Knoten Mittags versehentlich überschrieben und war erst vor zwei Stunden zum Redeployment von gpsplot gekommen.)

Bin offen für andere Lösungen.
